# -*- coding: utf-8 -*-
#
# -----------------------------------------------------------------------------
# focuser.py - Alpaca API responders for Focuser
#
# Author:   OnStepX Alpaca Driver Contributors
#
# Implements: ASCOM IFocuserV4 interface
#             https://ascom-standards.org/newdocs/focuser.html
# Python Compatibility: Requires Python 3.7 or later
#
# ??-???-????   Generated by Python Interface Generator for AlpycaDevice

from falcon import Request, Response, HTTPBadRequest, before
from logging import Logger
from shr import PropertyResponse, MethodResponse, PreProcessRequest, \
                StateValue, get_request_field, to_bool
from exceptions import *        # Nothing but exception classes
from focuserdevice import FocuserDevice
from onstepx_device import OnStepXDevice

logger: Logger = None
device: FocuserDevice = None
onstepx: OnStepXDevice = None

# ----------------------
# MULTI-INSTANCE SUPPORT
# ----------------------
# If this is > 0 then it means that multiple devices of this type are supported.
# Each responder on_get() and on_put() is called with a devnum parameter to indicate
# which instance of the device (0-based) is being called by the client. Leave this
# set to 0 for the simple case of controlling only one instance of this device type.
#
maxdev = 0                      # Single instance

# -----------
# DEVICE INFO
# -----------
# Static metadata not subject to configuration changes
class FocuserMetadata:
    """Metadata describing the Focuser Device."""
    Name = 'OnStepX Focuser'
    Version = '1.0.0'
    Description = 'ASCOM Alpaca Focuser for OnStepX Controller'
    DeviceType = 'Focuser'
    DeviceID = 'C9F4E5B3-8D0E-5F2C-B6G7-4E9D3F0A2C5B'
    Info = 'OnStepX Alpaca Driver\nImplements IFocuserV4\nASCOM Initiative'
    MaxDeviceNumber = maxdev
    InterfaceVersion = 4

# --------------------
# RESOURCE CONTROLLERS
# --------------------

@before(PreProcessRequest(maxdev))
class action:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandblind:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandbool:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandstring:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class connect:
    """Connect to the focuser device."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            device.connect()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Focuser.Connect failed', ex)).json

@before(PreProcessRequest(maxdev))
class connected:
    """Retrieves or sets the connected state of the device."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            is_conn = device.connected
            resp.text = PropertyResponse(is_conn, req).json
        except Exception as ex:
            resp.text = MethodResponse(req, DriverException(0x500, 'Focuser.Connected failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        conn_str = get_request_field('Connected', req)
        conn = to_bool(conn_str)              # Raises 400 Bad Request if str to bool fails

        try:
            if conn:
                device.connect()
            else:
                device.disconnect()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Focuser.Connected failed', ex)).json

@before(PreProcessRequest(maxdev))
class connecting:
    """True while the device is undertaking an asynchronous connect or disconnect operation."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            val = False  # Focuser connects synchronously
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Connecting failed', ex)).json

@before(PreProcessRequest(maxdev))
class description:
    """Description of the device such as manufacturer and model number."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(FocuserMetadata.Description, req).json

@before(PreProcessRequest(maxdev))
class devicestate:
    """List of StateValue objects representing the operational properties of this device."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return
        try:
            val = []
            val.append(StateValue('IsMoving', device.is_moving))
            val.append(StateValue('Position', device.position))
            val.append(StateValue('Temperature', device.temperature if device.temp_comp_available else None))
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Devicestate failed', ex)).json

@before(PreProcessRequest(maxdev))
class disconnect:
    """Disconnect from the focuser device."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            device.disconnect()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Focuser.Disconnect failed', ex)).json

@before(PreProcessRequest(maxdev))
class driverinfo:
    """Descriptive and version information about the ASCOM driver."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(FocuserMetadata.Info, req).json

@before(PreProcessRequest(maxdev))
class interfaceversion:
    """ASCOM Device interface definition version that this device supports."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(FocuserMetadata.InterfaceVersion, req).json

@before(PreProcessRequest(maxdev))
class driverversion:
    """String containing only the major and minor version of the driver."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(FocuserMetadata.Version, req).json

@before(PreProcessRequest(maxdev))
class name:
    """The short name of the driver, for display purposes."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(FocuserMetadata.Name, req).json

@before(PreProcessRequest(maxdev))
class supportedactions:
    """Returns the list of custom action names supported by this driver."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse([], req).json  # Not PropertyNotImplemented

# ============================================================================
# FOCUSER PROPERTIES (GET/PUT as specified)
# ============================================================================

@before(PreProcessRequest(maxdev))
class absolute:
    """True if focuser uses absolute positioning."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            val = device.absolute
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Absolute failed', ex)).json

@before(PreProcessRequest(maxdev))
class ismoving:
    """True if the focuser is currently moving."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            val = device.is_moving
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Ismoving failed', ex)).json

@before(PreProcessRequest(maxdev))
class maxincrement:
    """Maximum single move increment."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            val = device.max_increment
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Maxincrement failed', ex)).json

@before(PreProcessRequest(maxdev))
class maxstep:
    """Maximum focuser position."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            val = device.max_step
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Maxstep failed', ex)).json

@before(PreProcessRequest(maxdev))
class position:
    """Current focuser position."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            val = device.position
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Position failed', ex)).json

@before(PreProcessRequest(maxdev))
class stepsize:
    """Conversion factor from steps to physical units."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            val = device.step_size
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Stepsize failed', ex)).json

@before(PreProcessRequest(maxdev))
class tempcomp:
    """Temperature compensation enabled status."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            val = device.temp_comp
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Tempcomp failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        tempcompstr = get_request_field('TempComp', req)      # Raises 400 bad request if missing
        try:
            tempcomp = to_bool(tempcompstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'TempComp {tempcompstr} not a valid boolean.')).json
            return

        try:
            device.temp_comp = tempcomp
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Focuser.Tempcomp failed', ex)).json

@before(PreProcessRequest(maxdev))
class tempcompavailable:
    """True if temperature compensation is available."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            val = device.temp_comp_available
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Tempcompavailable failed', ex)).json

@before(PreProcessRequest(maxdev))
class temperature:
    """Focuser temperature from sensor."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            val = device.temperature
            resp.text = PropertyResponse(val, req).json
        except PropertyNotImplementedException as ex:
            resp.text = PropertyResponse(None, req, ex).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Focuser.Temperature failed', ex)).json

# ============================================================================
# FOCUSER METHODS (PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class halt:
    """Stop all focuser movement immediately."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        try:
            device.halt()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Focuser.Halt failed', ex)).json

@before(PreProcessRequest(maxdev))
class move:
    """Move focuser to absolute position."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req,
                            NotConnectedException()).json
            return

        positionstr = get_request_field('Position', req)      # Raises 400 bad request if missing
        try:
            position = int(positionstr)
        except:
            resp.text = MethodResponse(req,
                            InvalidValueException(f'Position {positionstr} not a valid integer.')).json
            return

        try:
            device.move(position)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Focuser.Move failed', ex)).json

# ============================================================================
# INITIALIZATION
# ============================================================================

def start_foc_device(config, _logger, shared_onstepx=None):
    """Initialize focuser device with shared OnStepX connection.

    Args:
        config: Configuration object
        _logger: Logger instance
        shared_onstepx: Shared OnStepXDevice instance (created by app.py)
    """
    global logger, device, onstepx
    logger = _logger

    # Use shared OnStepX connection if provided
    if shared_onstepx is not None:
        onstepx = shared_onstepx
    else:
        # Create new instance (backward compatibility)
        onstepx = OnStepXDevice(
            logger=logger,
            port=config.serial_port,
            baud=config.baud_rate,
            timeout=config.timeout,
            connection_type=config.connection_type,
            tcp_host=getattr(config, 'tcp_host', None),
            tcp_port=getattr(config, 'tcp_port', None)
        )

    # Initialize focuser device
    focuser_num = getattr(config, 'focuser_number', 1)
    device = FocuserDevice(logger, onstepx, focuser_num)
    logger.info(f'OnStepX Focuser {focuser_num} device initialized')
