# -*- coding: utf-8 -*-
#
# -----------------------------------------------------------------------------
# telescope.py - Alpaca API responders for Telescope
#
# Author:   OnStepX Alpaca Driver Contributors
#
# Implements: ASCOM ITelescopeV4 interface
#             https://ascom-standards.org/newdocs/telescope.html
# Python Compatibility: Requires Python 3.7 or later
#
# This is Part 1: Header section + CORE responders only
#
# ??-???-????   Generated by Python Interface Generator for AlpycaDevice

from falcon import Request, Response, HTTPBadRequest, before
from logging import Logger
from shr import PropertyResponse, MethodResponse, PreProcessRequest, \
                StateValue, get_request_field, to_bool
from exceptions import *        # Nothing but exception classes
from telescopedevice import TelescopeDevice

logger: Logger = None
device: TelescopeDevice = None

# ----------------------
# MULTI-INSTANCE SUPPORT
# ----------------------
# If this is > 0 then it means that multiple devices of this type are supported.
# Each responder on_get() and on_put() is called with a devnum parameter to indicate
# which instance of the device (0-based) is being called by the client. Leave this
# set to 0 for the simple case of controlling only one instance of this device type.
#
maxdev = 0                      # Single instance

# -----------
# DEVICE INFO
# -----------
# Static metadata not subject to configuration changes
class TelescopeMetadata:
    """ Metadata describing the Telescope Device. """
    Name = 'OnStepX Telescope'
    Version = '1.0.0'
    Description = 'ASCOM Alpaca Driver for OnStepX Controller'
    DeviceType = 'Telescope'
    DeviceID = 'A3F8B2D1-4C7E-4A1F-9B3D-2E8F5C6A1D9E'
    Info = 'OnStepX Alpaca Driver\nImplements ITelescopeV4\nASCOM Initiative'
    MaxDeviceNumber = maxdev
    InterfaceVersion = 4

# --------------
# SYMBOLIC ENUMS
# --------------
#
from enum import IntEnum

class AlignmentModes(IntEnum):
    algAltAz        = 0,
    algPolar        = 1,
    algGermanPolar  = 2

class DriveRates(IntEnum):
    driveSidereal   = 0,
    driveLunar      = 1,
    driveSolar      = 2,
    driveKing       = 3

class EquatorialCoordinateType(IntEnum):
    equOther        = 0,
    equTopocentric  = 1,
    equJ2000        = 2,
    equJ2050        = 3,
    equB1950        = 4

class GuideDirections(IntEnum):    # Shared by Camera
    guideNorth      = 0,
    guideSouth      = 1,
    guideEast       = 2,
    guideWest       = 3

class PierSide(IntEnum):
    pierEast        = 0,
    pierWest        = 1,
    pierUnknown     = -1

class TelescopeAxes(IntEnum):
    axisPrimary     = 0,
    axisSecondary   = 1,
    axisTertiary    = 2

# --------------------
# RESOURCE CONTROLLERS
# --------------------

@before(PreProcessRequest(maxdev))
class action:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandblind:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandbool:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class commandstring:
    def on_put(self, req: Request, resp: Response, devnum: int):
        resp.text = MethodResponse(req, NotImplementedException()).json

@before(PreProcessRequest(maxdev))
class connect:
    """Connect to the telescope device.

    See https://ascom-standards.org/newdocs/telescope.html#Telescope.Connect
    """
    def on_put(self, req: Request, resp: Response, devnum: int):
        try:
            device.connect()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Connect failed', ex)).json

@before(PreProcessRequest(maxdev))
class connected:
    """Retrieves or sets the connected state of the device.

    See https://ascom-standards.org/newdocs/telescope.html#Telescope.Connected
    """
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            is_conn = device._connected
            resp.text = PropertyResponse(is_conn, req).json
        except Exception as ex:
            resp.text = MethodResponse(req, DriverException(0x500, 'Telescope.Connected failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        conn_str = get_request_field('Connected', req)
        conn = to_bool(conn_str)              # Raises 400 Bad Request if str to bool fails

        try:
            if conn:
                device.connect()
            else:
                device.disconnect()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                            DriverException(0x500, 'Telescope.Connected failed', ex)).json

@before(PreProcessRequest(maxdev))
class connecting:
    """True while the device is undertaking an asynchronous connect or disconnect operation.

    See https://ascom-standards.org/newdocs/telescope.html#Telescope.Connecting
    """
    def on_get(self, req: Request, resp: Response, devnum: int):
        try:
            val = device.connecting if hasattr(device, 'connecting') else False
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                            DriverException(0x500, 'Telescope.Connecting failed', ex)).json

@before(PreProcessRequest(maxdev))
class description:
    """Description of the device such as manufacturer and model number.

    See https://ascom-standards.org/newdocs/telescope.html#Telescope.Description
    """
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(TelescopeMetadata.Description, req).json

@before(PreProcessRequest(maxdev))
class driverinfo:
    """Descriptive and version information about the ASCOM driver.

    See https://ascom-standards.org/newdocs/telescope.html#Telescope.DriverInfo
    """
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(TelescopeMetadata.Info, req).json

@before(PreProcessRequest(maxdev))
class driverversion:
    """String containing only the major and minor version of the driver.

    See https://ascom-standards.org/newdocs/telescope.html#Telescope.DriverVersion
    """
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(TelescopeMetadata.Version, req).json

@before(PreProcessRequest(maxdev))
class interfaceversion:
    """ASCOM Device interface definition version that this device supports.
    Should return 4 for this interface version ITelescopeV4.

    See https://ascom-standards.org/newdocs/telescope.html#Telescope.InterfaceVersion
    """
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(TelescopeMetadata.InterfaceVersion, req).json

@before(PreProcessRequest(maxdev))
class name:
    """The short name of the driver, for display purposes.

    See https://ascom-standards.org/newdocs/telescope.html#Telescope.Name
    """
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(TelescopeMetadata.Name, req).json

@before(PreProcessRequest(maxdev))
class supportedactions:
    """Returns the list of custom action names, to be used with Action(),
    supported by this driver.

    See https://ascom-standards.org/newdocs/telescope.html#Telescope.SupportedActions
    """
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse([], req).json  # Not PropertyNotImplemented

# ============================================================================
# POSITION (GET only)
# ============================================================================

@before(PreProcessRequest(maxdev))
class rightascension:
    """Right ascension of the mount (hours, 0-24)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.right_ascension
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.RightAscension failed', ex)).json

@before(PreProcessRequest(maxdev))
class declination:
    """Declination of the mount (degrees, -90 to +90)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.declination
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.Declination failed', ex)).json

@before(PreProcessRequest(maxdev))
class altitude:
    """Altitude of the mount (degrees)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.altitude
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.Altitude failed', ex)).json

@before(PreProcessRequest(maxdev))
class azimuth:
    """Azimuth of the mount (degrees, 0-360)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.azimuth
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.Azimuth failed', ex)).json

# ============================================================================
# TARGET (GET/PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class targetrightascension:
    """Target right ascension (hours, 0-24)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.target_right_ascension
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.TargetRightAscension read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = float(get_request_field('TargetRightAscension', req))
            device.target_right_ascension = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.TargetRightAscension write failed', ex)).json

@before(PreProcessRequest(maxdev))
class targetdeclination:
    """Target declination (degrees, -90 to +90)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.target_declination
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.TargetDeclination read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = float(get_request_field('TargetDeclination', req))
            device.target_declination = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.TargetDeclination write failed', ex)).json

# ============================================================================
# STATE (GET only except tracking)
# ============================================================================

@before(PreProcessRequest(maxdev))
class slewing:
    """True if the telescope is slewing."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.slewing
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.Slewing failed', ex)).json

@before(PreProcessRequest(maxdev))
class atpark:
    """True if the telescope is parked."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.at_park
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.AtPark failed', ex)).json

@before(PreProcessRequest(maxdev))
class athome:
    """True if the telescope is at home."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.at_home
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.AtHome failed', ex)).json

@before(PreProcessRequest(maxdev))
class ispulseguiding:
    """True if pulse guiding is in progress."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.is_pulse_guiding
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.IsPulseGuiding failed', ex)).json

@before(PreProcessRequest(maxdev))
class tracking:
    """Enable or disable tracking."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.tracking
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.Tracking read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = to_bool(get_request_field('Tracking', req))
            device.tracking = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.Tracking write failed', ex)).json

# ============================================================================
# PIER (GET, sideofpier also PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class sideofpier:
    """Side of pier (0=east, 1=west, -1=unknown)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.side_of_pier
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.SideOfPier read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = int(get_request_field('SideOfPier', req))
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SideOfPier write failed', ex)).json

@before(PreProcessRequest(maxdev))
class destinationsideofpier:
    """Destination side of pier for slew."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.destination_side_of_pier
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.DestinationSideOfPier failed', ex)).json

# ============================================================================
# SITE (GET/PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class sitelatitude:
    """Site latitude (degrees, -90 to +90)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.site_latitude
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.SiteLatitude read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = float(get_request_field('SiteLatitude', req))
            device.site_latitude = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SiteLatitude write failed', ex)).json

@before(PreProcessRequest(maxdev))
class sitelongitude:
    """Site longitude (degrees, -180 to +180)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.site_longitude
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.SiteLongitude read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = float(get_request_field('SiteLongitude', req))
            device.site_longitude = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SiteLongitude write failed', ex)).json

@before(PreProcessRequest(maxdev))
class siteelevation:
    """Site elevation (meters)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.site_elevation
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.SiteElevation read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = float(get_request_field('SiteElevation', req))
            device.site_elevation = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SiteElevation write failed', ex)).json

# ============================================================================
# TIME
# ============================================================================

@before(PreProcessRequest(maxdev))
class siderealtime:
    """Local sidereal time (hours, 0-24)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.sidereal_time
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.SiderealTime failed', ex)).json

@before(PreProcessRequest(maxdev))
class utcdate:
    """UTC date/time."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.utc_date
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.UTCDate read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = get_request_field('UTCDate', req)
            device.utc_date = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.UTCDate write failed', ex)).json

# ============================================================================
# MOUNT (GET only)
# ============================================================================

@before(PreProcessRequest(maxdev))
class alignmentmode:
    """Alignment mode (0=AltAz, 1=Polar, 2=GermanPolar)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.alignment_mode
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.AlignmentMode failed', ex)).json

@before(PreProcessRequest(maxdev))
class aperturearea:
    """Aperture area (square cm)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.aperture_area
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.ApertureArea failed', ex)).json

@before(PreProcessRequest(maxdev))
class aperturediameter:
    """Aperture diameter (cm)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.aperture_diameter
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.ApertureDiameter failed', ex)).json

@before(PreProcessRequest(maxdev))
class focallength:
    """Focal length (mm)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.focal_length
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.FocalLength failed', ex)).json

@before(PreProcessRequest(maxdev))
class doesrefraction:
    """True if refraction correction is performed."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.does_refraction
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.DoesRefraction failed', ex)).json

@before(PreProcessRequest(maxdev))
class equatorialsystem:
    """Equatorial coordinate system (1=topocentric, 2=J2000, etc)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.equatorial_system
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.EquatorialSystem failed', ex)).json

# ============================================================================
# TRACKING (GET/PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class trackingrate:
    """Tracking rate (0=sidereal, 1=lunar, 2=solar, 3=king)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.tracking_rate
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.TrackingRate read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = int(get_request_field('TrackingRate', req))
            device.tracking_rate = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.TrackingRate write failed', ex)).json

@before(PreProcessRequest(maxdev))
class trackingrates:
    """Array of available tracking rates."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.tracking_rates
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.TrackingRates failed', ex)).json

@before(PreProcessRequest(maxdev))
class declinationrate:
    """Declination tracking rate offset (arcsec/sec)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.declination_rate
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.DeclinationRate read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = float(get_request_field('DeclinationRate', req))
            device.declination_rate = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.DeclinationRate write failed', ex)).json

@before(PreProcessRequest(maxdev))
class rightascensionrate:
    """Right ascension tracking rate offset (sec/sidereal-sec)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.right_ascension_rate
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.RightAscensionRate read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = float(get_request_field('RightAscensionRate', req))
            device.right_ascension_rate = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.RightAscensionRate write failed', ex)).json

# ============================================================================
# GUIDE (GET/PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class guideratedeclination:
    """Declination guide rate (fraction of sidereal)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.guide_rate_declination
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.GuideRateDeclination read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = float(get_request_field('GuideRateDeclination', req))
            device.guide_rate_declination = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.GuideRateDeclination write failed', ex)).json

@before(PreProcessRequest(maxdev))
class guideraterightascension:
    """Right ascension guide rate (fraction of sidereal)."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            val = device.guide_rate_right_ascension
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.GuideRateRightAscension read failed', ex)).json

    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            val = float(get_request_field('GuideRateRightAscension', req))
            device.guide_rate_right_ascension = val
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.GuideRateRightAscension write failed', ex)).json

# ============================================================================
# CAPABILITIES (all GET only, return device.can_xxx)
# ============================================================================

@before(PreProcessRequest(maxdev))
class canfindhome:
    """True if the mount can find home."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_find_home, req).json

@before(PreProcessRequest(maxdev))
class canpark:
    """True if the mount can park."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_park, req).json

@before(PreProcessRequest(maxdev))
class canpulseguide:
    """True if the mount can pulse guide."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_pulse_guide, req).json

@before(PreProcessRequest(maxdev))
class cansetguiderates:
    """True if guide rates can be set."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_set_guide_rates, req).json

@before(PreProcessRequest(maxdev))
class cansetpark:
    """True if park position can be set."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_set_park, req).json

@before(PreProcessRequest(maxdev))
class cansetpierside:
    """True if pier side can be set."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_set_pier_side, req).json

@before(PreProcessRequest(maxdev))
class cansettracking:
    """True if tracking can be set."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_set_tracking, req).json

@before(PreProcessRequest(maxdev))
class canslew:
    """True if the mount can slew."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_slew, req).json

@before(PreProcessRequest(maxdev))
class canslewasync:
    """True if the mount can slew asynchronously."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_slew_async, req).json

@before(PreProcessRequest(maxdev))
class canslewaltaz:
    """True if the mount can slew to Alt/Az."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_slew_alt_az, req).json

@before(PreProcessRequest(maxdev))
class canslewaltazasync:
    """True if the mount can slew to Alt/Az asynchronously."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_slew_alt_az_async, req).json

@before(PreProcessRequest(maxdev))
class cansync:
    """True if the mount can sync."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_sync, req).json

@before(PreProcessRequest(maxdev))
class cansyncaltaz:
    """True if the mount can sync to Alt/Az."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_sync_alt_az, req).json

@before(PreProcessRequest(maxdev))
class canunpark:
    """True if the mount can unpark."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_unpark, req).json

@before(PreProcessRequest(maxdev))
class canmoveaxis:
    """True if the mount can move axis."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        resp.text = PropertyResponse(device.can_move_axis, req).json

# ============================================================================
# SLEW METHODS (PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class abortslew:
    """Abort any slew operation."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            device.abort_slew()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.AbortSlew failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewtocoordinates:
    """Slew to specified RA/Dec (blocking)."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            ra = float(get_request_field('RightAscension', req))
            dec = float(get_request_field('Declination', req))
            device.slew_to_coordinates(ra, dec)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SlewToCoordinates failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewtocoordinatesasync:
    """Slew to specified RA/Dec (async)."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            ra = float(get_request_field('RightAscension', req))
            dec = float(get_request_field('Declination', req))
            device.slew_to_coordinates_async(ra, dec)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SlewToCoordinatesAsync failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewtotarget:
    """Slew to current target (blocking)."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            device.slew_to_target()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SlewToTarget failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewtotargetasync:
    """Slew to current target (async)."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            device.slew_to_target_async()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SlewToTargetAsync failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewtoaltaz:
    """Slew to specified Alt/Az (blocking)."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            alt = float(get_request_field('Altitude', req))
            az = float(get_request_field('Azimuth', req))
            device.slew_to_alt_az(az, alt)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SlewToAltAz failed', ex)).json

@before(PreProcessRequest(maxdev))
class slewtoaltazasync:
    """Slew to specified Alt/Az (async)."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            alt = float(get_request_field('Altitude', req))
            az = float(get_request_field('Azimuth', req))
            device.slew_to_alt_az_async(az, alt)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SlewToAltAzAsync failed', ex)).json

# ============================================================================
# PARK/HOME (PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class park:
    """Park the mount."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            device.park()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.Park failed', ex)).json

@before(PreProcessRequest(maxdev))
class setpark:
    """Set current position as park position."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            device.set_park()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SetPark failed', ex)).json

@before(PreProcessRequest(maxdev))
class unpark:
    """Unpark the mount."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            device.unpark()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.Unpark failed', ex)).json

@before(PreProcessRequest(maxdev))
class findhome:
    """Find home position."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            device.find_home()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.FindHome failed', ex)).json

# ============================================================================
# SYNC (PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class synctocoordinates:
    """Sync to specified RA/Dec."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            ra = float(get_request_field('RightAscension', req))
            dec = float(get_request_field('Declination', req))
            device.sync_to_coordinates(ra, dec)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SyncToCoordinates failed', ex)).json

@before(PreProcessRequest(maxdev))
class synctotarget:
    """Sync to current target."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            device.sync_to_target()
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SyncToTarget failed', ex)).json

@before(PreProcessRequest(maxdev))
class synctoaltaz:
    """Sync to specified Alt/Az."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            alt = float(get_request_field('Altitude', req))
            az = float(get_request_field('Azimuth', req))
            device.sync_to_alt_az(az, alt)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.SyncToAltAz failed', ex)).json

# ============================================================================
# GUIDE (PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class pulseguide:
    """Start a pulse guide operation."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            direction = int(get_request_field('Direction', req))
            duration = int(get_request_field('Duration', req))
            device.pulse_guide(direction, duration)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.PulseGuide failed', ex)).json

# ============================================================================
# AXIS (GET, moveaxis PUT)
# ============================================================================

@before(PreProcessRequest(maxdev))
class axisrates:
    """Array of axis rates."""
    def on_get(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = PropertyResponse(None, req, NotConnectedException()).json
            return
        try:
            # Return array of rate objects (device doesn't implement this yet)
            val = []
            resp.text = PropertyResponse(val, req).json
        except Exception as ex:
            resp.text = PropertyResponse(None, req,
                DriverException(0x500, 'Telescope.AxisRates failed', ex)).json

@before(PreProcessRequest(maxdev))
class moveaxis:
    """Move axis at specified rate."""
    def on_put(self, req: Request, resp: Response, devnum: int):
        if not device.connected:
            resp.text = MethodResponse(req, NotConnectedException()).json
            return
        try:
            axis = int(get_request_field('Axis', req))
            rate = float(get_request_field('Rate', req))
            device.move_axis(axis, rate)
            resp.text = MethodResponse(req).json
        except Exception as ex:
            resp.text = MethodResponse(req,
                DriverException(0x500, 'Telescope.MoveAxis failed', ex)).json

# ============================================================================
# INITIALIZATION
# ============================================================================

def start_tel_device(config, _logger, onstepx=None):
    """Initialize telescope device with shared OnStepX connection.

    Args:
        config: Configuration object
        _logger: Logger instance
        onstepx: Shared OnStepXDevice instance (created by app.py)
    """
    global logger, device
    logger = _logger
    device = TelescopeDevice(logger, config, onstepx)
    logger.info('Telescope device initialized')
